SpookVooper/Controllers/ForumController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using SpookVooper.Web.Models.ForumViewModels;
using SpookVooper.Web.Models.ManageViewModels;
using SpookVooper.Web.Helpers;
using SpookVooper.Web.Entities;
using SpookVooper.Web.DB;
using SpookVooper.Web.Forums;
using SpookVooper.Web.Entities.Groups;

namespace SpookVooper.Web.Controllers
{
    public class ForumController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private RoleManager<IdentityRole> _roleManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        public ForumController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            VooperContext context,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler,
            RoleManager<IdentityRole> roleManager)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
            _roleManager = roleManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> Index(string id, int page)
        {
            if (String.IsNullOrEmpty(id))
            {
                id = "Root";
            }

            ForumIndexViewModel model = new ForumIndexViewModel()
            {
                Category = id,
                userManager = _userManager,
                amount = 10,
                page = page
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Admin()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> AddCategory()
        {
            CategoryViewModel model = new CategoryViewModel();

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategory(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _context.ForumCategories.Add(new ForumCategory()
            {
                CategoryID = model.Name,
                Description = model.Description,
                Tags = model.Tags,
                Parent = model.Parent
            });

            StatusMessage = $"Successfully added the category {model.Name}.";

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> EditCategory(string id)
        {

            ForumCategory current = _context.ForumCategories.FirstOrDefault(c => c.CategoryID == id);

            if (current == null)
            {
                StatusMessage = $"Error: The category {id} does not exist!";
                return RedirectToAction(nameof(Index));
            }

            CategoryViewModel model = new CategoryViewModel()
            {
                Name = current.CategoryID,
                Description = current.Description,
                Tags = current.Tags,
                Parent = current.Parent,
                RoleAccess = current.RoleAccess
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCategory(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            ForumCategory category = _context.ForumCategories.FirstOrDefault(c => c.CategoryID == model.Name);

            category.CategoryID = model.Name;
            category.Description = model.Description;
            category.Tags = model.Tags;
            category.Parent = model.Parent;
            category.RoleAccess = model.RoleAccess;

            StatusMessage = $"Successfully edited the category {model.Name}.";

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AddPost(string id, bool picpost)
        {

            ForumCategory category = _context.ForumCategories.FirstOrDefault(c => c.CategoryID == id);

            if (category == null)
            {
                StatusMessage = $"Failed to find the category {id}.";
                return RedirectToAction(nameof(Index));
            }

            User user = null;

            if (User != null)
            {
                user = await _userManager.GetUserAsync(User);
            }

            // Group check: Ensure that if this is a group category, the poster is a member!
            Group group = _context.Groups.FirstOrDefault(g => category.CategoryID == g.Name);

            if (group != null)
            {
                if (!await group.IsInGroup(user))
                {
                    StatusMessage = $"Error: You must be a part of the group to post here! Ensure you are logged in.";
                    return RedirectToAction(nameof(Index));
                }
            }

            if (RoleHelper.UserAuthorizedForCategory(_roleManager, category, User))
            {
                PostViewModel model = new PostViewModel();
                model.Category = id;
                model.Picture = picpost;

                return View(model);
            }
            else
            {
                StatusMessage = $"Error: You are not authorized to create a post in {id}.";
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost(PostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = await _userManager.GetUserAsync(User);

            ForumCategory category = _context.ForumCategories.FirstOrDefault(c => c.CategoryID == model.Category);

            if (category == null)
            {
                StatusMessage = $"Error: Failed to find the category {model.Category}.";
                return RedirectToAction(nameof(Index));
            }

            if (RoleHelper.UserAuthorizedForCategory(_roleManager, category, User))
            {

                // Check for group ownership and permissions
                Group group = _context.Groups.FirstOrDefault(g => category.CategoryID.ToLower() == g.Name.ToLower());

                if (group != null)
                {
                    if (!await group.HasPermissionAsync(user, "post"))
                    {
                        StatusMessage = $"Error: You don't have permission to post in this group!";
                        return RedirectToAction(nameof(Index));
                    }
                }

                model.PostID = (ulong)_context.ForumPosts.LongCount();
                model.TimePosted = DateTime.UtcNow;
                model.Author = user.Id;

                if (model.Picture)
                {
                    model.Content = model.ImageLink;
                }

                _context.ForumPosts.Add(new ForumPost()
                {
                    Author = model.Author,
                    Category = model.Category,
                    Content = model.Content,
                    PostID = model.PostID,
                    Tags = model.Tags,
                    TimePosted = model.TimePosted,
                    Title = model.Title,
                    Picture = model.Picture
                });

                await _context.SaveChangesAsync();

                if (model.Picture)
                {
                    await VoopAI.forumChannel.SendMessageAsync($"New Picture Post! \n https://SpookVooper.com/Forum/ViewPost/{model.PostID}");
                }
                else { 
                    await VoopAI.forumChannel.SendMessageAsync($"New Post! \n https://SpookVooper.com/Forum/ViewPost/{model.PostID}");
                }

                StatusMessage = $"Post created successfully!";
                return RedirectToAction(nameof(ViewPost), new { id = model.PostID });
            }
            else
            {
                StatusMessage = $"Error: You are not authorized to create a post in {category.CategoryID}. [POST Request]";
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> RemovePost(ulong id)
        {

            ForumPost post = _context.ForumPosts.FirstOrDefault(p => p.PostID == id);

            if (post == null)
            {
                StatusMessage = $"Failed to find post with id {id}.";
                return RedirectToAction(nameof(Index));
            }

            User user = await _userManager.GetUserAsync(User);

            if (!(User.IsInRole("Admin") || User.IsInRole("Moderator")))
            {
                if (post.Author != user.Id)
                {

SpookVooper/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.Services;
using System.Linq;
using System.Threading.Tasks;
using Discord.WebSocket;
using SpookVooper.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using SpookVooper.Web.Entities;
using SpookVooper.Web.DB;

namespace SpookVooper.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        public UserController(
            VooperContext context,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string id)
        {
            UserSearchModel model = new UserSearchModel()
            {
                userManager = _userManager,
                search = id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(UserSearchModel model)
        {
            model.userManager = _userManager;

            return RedirectToAction(nameof(Search), routeValues: new { id = model.search });
        }

        [HttpGet]
        public async Task<IActionResult> Info(string svid)
        {
            if (svid == null)
            {
                return View(null);
            }

            User webUser = await _userManager.FindByIdAsync(svid);

            return View(webUser);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> SetInfo()
        {
            User webuser = await _userManager.GetUserAsync(User);

            if (webuser == null)
            {
                return RedirectToAction(nameof(Info));
            }

            SetInfoViewModel model = new SetInfoViewModel()
            {
                Description = webuser.description,
                userManager = _userManager
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetInfo(SetInfoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                model.StatusMessage = "Failed to set: User instance not found!";
                return View(model);
            }

            if (model.Description.Length < 1000)
            {
                user.description = model.Description;
            }
            else
            {
                model.StatusMessage = "Error: The entered description is over 1000 characters!";
                return View(model);
            }

            await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(SetInfo));
        }

        public async Task<IActionResult> GetSVIDFromUsername(string username)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.UserName == username));

            if (user == null) return NotFound($"Could not find user {username}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> GetUsernameFromDiscord(ulong discordid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.discord_id == discordid));

            if (user == null) return NotFound($"Could not find user with discord {discordid}");

            return Ok(user.UserName);
        }

        public async Task<IActionResult> GetSVIDFromDiscord(ulong discordid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.discord_id == discordid));

            if (user == null) return NotFound($"Could not find user with discord {discordid}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> GetUsernameFromMinecraft(string minecraftid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.minecraft_id == minecraftid));

            if (user == null) return NotFound($"Could not find user with minecraft {minecraftid}");

            return Ok(user.UserName);
        }

        public async Task<IActionResult> GetSVIDFromMinecraft(string minecraftid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.minecraft_id == minecraftid));

            if (user == null) return NotFound($"Could not find user with minecraft {minecraftid}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> HasDiscordRole(string userid, string role)
        {
            User user = await _userManager.FindByIdAsync(userid);

            if (user == null) return NotFound($"Could not find {userid}");
            else
            {
                SocketGuildUser discordUser = VoopAI.server.Users.FirstOrDefault(u => u.Id == user.discord_id);

                if (discordUser == null) return NotFound($"User has no linked discord account!");

                else return Ok(discordUser.Roles.Any(r => r.Name.ToLower() == role.ToLower()));
            }
        }

        public async Task<IActionResult> GetDiscordRoles(string userid)
        {
            User user = await _userManager.FindByIdAsync(userid);

            if (user == null) return NotFound($"Could not find user {userid}.");

            if (user.discord_id == null) return NotFound($"User does not have a linked discord.");

            var roles = VoopAI.server.GetUser((ulong)user.discord_id).Roles;

            string data = "";

            if (roles.Count > 0)
            {
                foreach (var role in roles)
                {
                    data += role.Name + "|";
                }

                data = data.Substring(0, data.Length - 1);
            }

            return Ok(data);

        }
    }
}

SpookVooper/Views/Forum/AddCategory.cshtml
@model CategoryViewModel
@inject VooperContext context
@{
    ViewData["Title"] = "Add Category";
}

<div class="container vw-100">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])
        <div class="row">
            <div class="col-md-6">
                <form method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Tags"></label>
                        <input asp-for="Tags" class="form-control" />
                        <span asp-validation-for="Tags" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RoleAccess"></label>
                        <input asp-for="RoleAccess" class="form-control" />
                        <span asp-validation-for="RoleAccess" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Parent"></label>
                        <br />
                        <select class="form-control" asp-for="Parent" asp-items="context.GetForumCategoryListForDropdown()"></select>
                    </div>
                    <br />

                    <div class="form-group">
                        <div class="container" style="align-content:flex-start">
                            <div class="d-flex">
                                <div class="flex-column" style="margin-right:5px; margin-left: -15px">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        @section Scripts {
            @await Html.PartialAsync("_ValidationScriptsPartial")
        }
    </div>
</div>

SpookVooper/Views/Forum/AddPost.cshtml
@model PostViewModel
@{
    ViewData["Title"] = "Add Post";
}

<div class="container vw-100">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])


        <form method="post">
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Tags"></label>
                        <input asp-for="Tags" class="form-control" />
                        <span asp-validation-for="Tags" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.HiddenFor(x => x.Category)
                        <label asp-for="Category"></label>
                        <input asp-for="Category" class="form-control" disabled />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Handle picture posts differently for validation -->
                @Html.HiddenFor(x => x.Picture)
                <div class="col-md-10">
                    @if (!Model.Picture)
                    {
                        <div class="form-group">
                            <label asp-for="Content"></label>
                            <textarea asp-for="Content" rows="6" class="form-control"> </textarea>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                    }
                    else
                    {
                        <div class="form-group">
                            <label asp-for="ImageLink"></label>
                            <textarea asp-for="ImageLink" rows="2" class="form-control"> </textarea>
                            <span asp-validation-for="ImageLink" class="text-danger"></span>
                        </div>
                    }
                </div>
                <br />
            </div>

            <div class="form-group">
                <div class="container" style="align-content:flex-start">
                    <div class="d-flex">
                        <div class="flex-column" style="margin-right:5px; margin-left: -15px">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }
</div>

SpookVooper/Views/Forum/Index.cshtml
@using Discord.WebSocket;
@model SpookVooper.Web.Models.ForumViewModels.ForumIndexViewModel
@inject VooperContext context
@{
    if (@String.IsNullOrEmpty(Model.Category))
    {
        ViewData["Title"] = "Forums";
    }
    else
    {
        ViewData["Title"] = @Model.Category;
    }

}

<div class="container vw-100">
    @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])

    @{
        IEnumerable<ForumCategory> cats = context.ForumCategories.AsQueryable().Where(c => c.Parent == Model.Category);
        List<ForumPost> posts = context.ForumPosts.AsQueryable().Where(c => c.Category == Model.Category && !c.Removed).AsEnumerable().OrderByDescending(p => p.GetWeight(context)).ToList();
        IEnumerable<ForumPost> recentposts = null;

        int start = Model.page * Model.amount;

        <br />

        if (Model.Category == "Root")
        {
            recentposts = context.ForumPosts.AsQueryable().Where(c => !c.Removed).AsEnumerable().OrderBy(c => DateTime.UtcNow.Subtract(c.TimePosted).TotalSeconds).Take(5);
        }
        else
        {
            ForumCategory thisCat = context.ForumCategories.FirstOrDefault(c => c.CategoryID == Model.Category);

            if (thisCat != null && thisCat.Parent != null)
            {
            <a class="h1" style="font-size:larger; margin-bottom:20px" asp-controller="Forum" asp-action="Index" asp-route-id="@thisCat.Parent">
                Back: @thisCat.Parent
            </a>
            }

            recentposts = context.ForumPosts.AsQueryable().Where(c => !c.Removed && c.Category == @Model.Category).AsEnumerable().OrderBy(c => DateTime.UtcNow.Subtract(c.TimePosted).TotalSeconds).Take(5);
        }

        if (cats.Count() + posts.Count() == 0)
        {
            <h1 class="text-center">There's nothing here.</h1>
            <h2 class="text-center">Maybe you should post something to fix that.</h2>
        }
        else
        {

            <div class="d-flex flex-wrap justify-content-center" style="margin-top:20px">
                @foreach (ForumCategory cat in cats)
                {
                    <div class="d-flex flex-column flex-wrap forumlistcard flex-shrink-0 flex-grow-1 p-2">
                        <div class="p-1">
                            <a style="font-size:larger" asp-controller="Forum" asp-action="Index" asp-route-id="@cat.CategoryID">
                                @cat.CategoryID
                            </a>
                        </div>
                        <div class="p-1">
                            @cat.Description
                        </div>
                        <div class="p-1" style="font-size:smaller">
                            @cat.Tags
                        </div>
                    </div>
                }
            </div>

            <br />
            <h2>Posts</h2>

            User user = null;

            if (User != null)
            {
                user = await Model.userManager.GetUserAsync(User);
            }


            for (int i = start; i < start + Model.amount; i++)
            {
                if (i > posts.Count() - 1)
                {
                    break;
                }

                ForumPost post = posts[i];

                <div class="d-flex flex-wrap srow">
                    <div class="p-2" style="font-size:larger">
                        💙 @post.GetLikes(context)
                    </div>
                    <div class="p-2" style="width:40%">

                        <a style="font-size:larger" asp-controller="Forum" asp-action="ViewPost" asp-route-id="@post.PostID">
                            @Html.Raw(StringHelper.FormatTitle(post.Title, 20))
                        </a>
                    </div>

                    <div class="p-0 flex-grow-1">
                        <div class="d-flex">
                            @{
                                User authorUser = await Model.userManager.FindByIdAsync(post.Author);
                                <div class="p-1">
                                    <img class="smallpfp" style="margin-left: 10px; margin-right:10px; float:right" src="@authorUser.GetPfpUrl()" />
                                </div>
                                <a asp-controller="User" asp-action="Info" asp-route-id="@authorUser.UserName">
                                    <p class="forumtable-text">@authorUser.UserName</p>
                                </a>
                            }
                        </div>
                    </div>

                    <div class="p-2" style="min-width:25%">
                        <p style="word-break:break-all">
                            @Html.Raw(StringHelper.FormatTitle(post.Content, 30))
                        </p>
                    </div>
                    <!--
                        <div class="col-3">
                            <p style="font-size:smaller">
                                @post.Tags
                            </p>
                        </div>
                    -->

                </div>





            }

                <br />

            }

            <div class="d-flex">
                <div class="p-1 align-self-start flex-grow-1">
                    <h1></h1>
                </div>
                @if (Model.page != 0)
                {
                    <div class="p-2 align-self-end">
                        <a asp-action="Index" asp-controller="Forum" asp-route-id="@Model.Category" asp-route-page="@(Model.page - 1)" class="btn btn-primary" style="white-space:nowrap">Last</a>
                    </div>
                }
                @if ((Model.page + 1) * Model.amount < posts.Count() - 1)
                {
                    <div class="p-2 align-self-end">
                        <a asp-action="Index" asp-controller="Forum" asp-route-id="@Model.Category" asp-route-page="@(Model.page + 1)" class="btn btn-primary" style="white-space:nowrap">Next</a>
                    </div>
                }
            </div>

            <div class="d-flex">
                <div class="p-2 flex-grow-1"></div>
                <div class="p-2">
                    <a class="btn btn-primary" asp-controller="Forum" asp-action="AddPost" asp-route-id="@Model.Category" asp-route-picpost="@false">Add Post</a>
                </div>
                <div class="p-2">
                    <a class="btn btn-primary" asp-controller="Forum" asp-action="AddPost" asp-route-id="@Model.Category" asp-route-picpost="@true">Add Image</a>
                </div>
            </div>

            <br />

            <h2>Recent</h2>

            foreach (ForumPost post in recentposts)
            {
                <div class="d-flex flex-wrap srow">
                    <div class="p-2" style="font-size:larger">
                        💙 @post.GetLikes(context)
                    </div>
                    <div class="p-2" style="width:40%">
                        <div class="d-flex flex-column">
                            <a style="font-size:larger" asp-controller="Forum" asp-action="ViewPost" asp-route-id="@post.PostID">
                                @Html.Raw(StringHelper.FormatTitle(post.Title, 20))
                            </a>
                            <a asp-controller="Forum" asp-action="Index" asp-route-id="@post.Category">in @post.Category</a>
                        </div>
                    </div>

                    <div class="p-0 flex-grow-1">
                        <div class="d-flex">
                            @{
                                User authorUser = await Model.userManager.FindByIdAsync(post.Author);
                                <div class="p-1">
                                    <img class="smallpfp" style="margin-left: 10px; margin-right:10px; float:right" src="@authorUser.GetPfpUrl()" />
                                </div>
                                <a asp-controller="User" asp-action="Info" asp-route-id="@authorUser.UserName">
                                    <p class="forumtable-text">@authorUser.UserName</p>
                                </a>
                            }
                        </div>
                    </div>

                    <div class="p-2" style="min-width:25%">
                        <p style="word-break:break-all">
                            @Html.Raw(StringHelper.FormatTitle(post.Content, 30))
                        </p>
                    </div>
                    <!--
                        <div class="col-3">
                            <p style="font-size:smaller">
                                @post.Tags
                            </p>
                        </div>
                    -->

                </div>



        }

    }
            </div>

SpookVooper/Views/Forum/RemovePost.cshtml
@model RemovePostModel
@{
    ViewData["Title"] = "Remove Post";
}

<div class="container vw-100">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])


    <form method="post">
        @Html.HiddenFor(x => x.PostID)

        <h1>Are you sure?</h1>

        <br/>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
    </div>
    @section Scripts {
        @await Html.PartialAsync("_ValidationScriptsPartial")
    }
</div>