SpookVooper/Controllers/LeaderboardController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Web.Entities;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.DB;
using SpookVooper.Web.Models.LeaderboardViewModels;
using SpookVooper.Web.Services;
using System.Threading.Tasks;

namespace SpookVooper.Web.Controllers
{
    public class LeaderboardController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        public LeaderboardController(
            VooperContext context,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
        }

        public async Task<IActionResult> Index(int id)
        {
            LeaderboardIndexModel model = null;

            await Task.Run(() =>
            {
                model = new LeaderboardIndexModel()
                {
                    users = VoopAI.leaderboard,
                    page = id,
                    amount = 25
                };
            });

             return View(model);

        }
    }
}

SpookVooper/Controllers/NerdcraftController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Web.Entities;
using SpookVooper.Data.Services;
using SpookVooper.Web.DB;
using SpookVooper.Web.Services;
using System.Threading.Tasks;

namespace SpookVooper.Web.Controllers
{
    public class NerdcraftController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private RoleManager<IdentityRole> _roleManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        [TempData]
        public string StatusMessage { get; set; }

        public NerdcraftController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler,
            VooperContext context,
            RoleManager<IdentityRole> roleManager)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _roleManager = roleManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> RulesGeneral()
        {
            return View();
        }

        public async Task<IActionResult> Laws()
        {
            return View();
        }

        public async Task<IActionResult> Jobs()
        {
            return View();
        }

        public async Task<IActionResult> Guide()
        {
            return View();
        }
    }
}

SpookVooper/Controllers/NewsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Discord.WebSocket;
using Microsoft.AspNetCore.Authorization;
using SpookVooper.Web.Helpers;
using Discord;
using SpookVooper.Web.Entities;
using SpookVooper.Web.DB;
using SpookVooper.Web.News;
using SpookVooper.Web.Entities.Groups;

namespace SpookVooper.Web.Controllers
{
    public class NewsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private RoleManager<IdentityRole> _roleManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        [TempData]
        public string StatusMessage { get; set; }

        public NewsController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler,
            VooperContext context,
            RoleManager<IdentityRole> roleManager)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
            _roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await Task.Run(() => View());
        }

        public async Task<IActionResult> View(string postid)
        {
            NewsPost post = await _context.NewsPosts.FindAsync(postid);

            return await Task.Run(() => View(post));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create (string groupid)
        {
            User user = await _userManager.GetUserAsync(User);
            Group group = await _context.Groups.FindAsync(groupid);

            if (group == null) return await RedirectBack($"Error: Could not find group {groupid}");

            if (! await PressPass.HasPressPass(group, _context)) return await RedirectBack($"Error: Group does not have a press pass!");

            if (!await group.HasPermissionAsync(user, "news")) return await RedirectBack($"Error: You do not have permission!");

            NewsPost post = new NewsPost()
            {
                PostID = Guid.NewGuid().ToString(),
                GroupID = groupid,
                AuthorID = user.Id
            };

            return View(post);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewsPost model)
        {
            if (!ModelState.IsValid) return View(model);

            User user = await _userManager.GetUserAsync(User);
            Group group = await _context.Groups.FindAsync(model.GroupID);

            if (group == null) return await RedirectBack($"Error: Could not find group {model.GroupID}");

            if (!await PressPass.HasPressPass(group, _context)) return await RedirectBack($"Error: Group does not have a press pass!");

            if (!await group.HasPermissionAsync(user, "news")) return await RedirectBack($"Error: You do not have permission!");

            model.Timestamp = DateTime.UtcNow;

            await _context.NewsPosts.AddAsync(model);
            await _context.SaveChangesAsync();

            SocketUser duser = user.GetDiscordSocket();
            if (duser == null) duser = VoopAI.discordClient.CurrentUser;

            EmbedBuilder embed = new EmbedBuilder()
            {
                Color = new Color(0, 100, 255),
                Title = $"**{model.Title}** by *{user.UserName}*"
            }
            .WithAuthor(duser)
            .WithCurrentTimestamp()
            .WithUrl($"https://spookvooper.com/News/View?postid={model.PostID}");

            embed.AddField("News Outlet", group.Name);
            embed.AddField("Author", user.UserName);
            embed.AddField("Content", $"{model.Content.Substring(0, Math.Min(model.Content.Length, 1000))}" + "...");

            VoopAI.newsChannel.SendMessageAsync(embed: embed.Build());

            return RedirectToAction("View", new { postid = model.PostID });
        }

        [Authorize]
        [AuthorizeDiscord("Minister of Journalism")]
        public async Task<IActionResult> AddPressPass(string groupid)
        {
            Group group = await _context.Groups.FindAsync(groupid);

            if (group == null) return await RedirectBack($"Failed to find group {groupid}");

            PressPass pass = new PressPass()
            {
                GroupID = groupid
            };

            await _context.PressPasses.AddAsync(pass);
            await _context.SaveChangesAsync();

            StatusMessage = $"Gave press pass to {group.Name}";
            return RedirectToAction("View", "Group", new { groupid = groupid });
        }

        [Authorize]
        [AuthorizeDiscord("Minister of Journalism")]
        public async Task<IActionResult> RemovePressPass(string groupid)
        {
            Group group = await _context.Groups.FindAsync(groupid);

            if (group == null) return await RedirectBack($"Failed to find group {groupid}");

            PressPass pass = await _context.PressPasses.FindAsync(groupid);

            if (pass == null) return await RedirectBack($"Failed: Group does not have a press pass!");

            _context.PressPasses.Remove(pass);
            await _context.SaveChangesAsync();

            StatusMessage = $"Removed press pass from {group.Name}";
            return RedirectToAction("View", "Group", new { groupid = groupid });
        }

        public async Task<IActionResult> RedirectBack(string reason)
        {
            StatusMessage = reason;
            return Redirect(Request.Headers["Referer"].ToString());
        }


    }
}

SpookVooper/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.Services;
using System.Linq;
using System.Threading.Tasks;
using Discord.WebSocket;
using SpookVooper.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using SpookVooper.Web.Entities;
using SpookVooper.Web.DB;

namespace SpookVooper.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        public UserController(
            VooperContext context,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string id)
        {
            UserSearchModel model = new UserSearchModel()
            {
                userManager = _userManager,
                search = id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(UserSearchModel model)
        {
            model.userManager = _userManager;

            return RedirectToAction(nameof(Search), routeValues: new { id = model.search });
        }

        [HttpGet]
        public async Task<IActionResult> Info(string svid)
        {
            if (svid == null)
            {
                return View(null);
            }

            User webUser = await _userManager.FindByIdAsync(svid);

            return View(webUser);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> SetInfo()
        {
            User webuser = await _userManager.GetUserAsync(User);

            if (webuser == null)
            {
                return RedirectToAction(nameof(Info));
            }

            SetInfoViewModel model = new SetInfoViewModel()
            {
                Description = webuser.description,
                userManager = _userManager
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetInfo(SetInfoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                model.StatusMessage = "Failed to set: User instance not found!";
                return View(model);
            }

            if (model.Description.Length < 1000)
            {
                user.description = model.Description;
            }
            else
            {
                model.StatusMessage = "Error: The entered description is over 1000 characters!";
                return View(model);
            }

            await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(SetInfo));
        }

        public async Task<IActionResult> GetSVIDFromUsername(string username)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.UserName == username));

            if (user == null) return NotFound($"Could not find user {username}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> GetUsernameFromDiscord(ulong discordid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.discord_id == discordid));

            if (user == null) return NotFound($"Could not find user with discord {discordid}");

            return Ok(user.UserName);
        }

        public async Task<IActionResult> GetSVIDFromDiscord(ulong discordid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.discord_id == discordid));

            if (user == null) return NotFound($"Could not find user with discord {discordid}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> GetUsernameFromMinecraft(string minecraftid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.minecraft_id == minecraftid));

            if (user == null) return NotFound($"Could not find user with minecraft {minecraftid}");

            return Ok(user.UserName);
        }

        public async Task<IActionResult> GetSVIDFromMinecraft(string minecraftid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.minecraft_id == minecraftid));

            if (user == null) return NotFound($"Could not find user with minecraft {minecraftid}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> HasDiscordRole(string userid, string role)
        {
            User user = await _userManager.FindByIdAsync(userid);

            if (user == null) return NotFound($"Could not find {userid}");
            else
            {
                SocketGuildUser discordUser = VoopAI.server.Users.FirstOrDefault(u => u.Id == user.discord_id);

                if (discordUser == null) return NotFound($"User has no linked discord account!");

                else return Ok(discordUser.Roles.Any(r => r.Name.ToLower() == role.ToLower()));
            }
        }

        public async Task<IActionResult> GetDiscordRoles(string userid)
        {
            User user = await _userManager.FindByIdAsync(userid);

            if (user == null) return NotFound($"Could not find user {userid}.");

            if (user.discord_id == null) return NotFound($"User does not have a linked discord.");

            var roles = VoopAI.server.GetUser((ulong)user.discord_id).Roles;

            string data = "";

            if (roles.Count > 0)
            {
                foreach (var role in roles)
                {
                    data += role.Name + "|";
                }

                data = data.Substring(0, data.Length - 1);
            }

            return Ok(data);

        }
    }
}

SpookVooper/Views/Shared/_Layout.cshtml
@inject UserManager<User> userManager

<!DOCTYPE html>
<html lang="en-us">
<head>
    <!--
     ___                _  __   __
    / __|_ __  ___  ___| |_\ \ / /__  ___ _ __  ___ _ _
    \__ \ '_ \/ _ \/ _ \ / /\ V / _ \/ _ \ '_ \/ -_) '_|
    |___/ .__/\___/\___/_\_\ \_/\___/\___/ .__/\___|_|
        |_|                              |_|

        Written by Spike Viper with love and care!
    -->
    <link rel="~/media/apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/media/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/media/favicon-16x16.png">
    <link rel="manifest" href="~/media/site.webmanifest">
    <link rel="mask-icon" href="~/media/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="description" content="A large community of online nerds looking to play games,
          make videos, and have some fun!">
    <meta name="keywords" content="Gaming,YouTube,Community,Forums">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta property="og:site_name" content="SpookVooper">
    <meta name="twitter:site" content="@@SpikeViperYT">
    <meta name="twitter:image:alt" content="Potato soldiers on a planet">
    <meta name="theme-color" content="#3948ed">

    <title>@ViewData["Title"] - SpookVooper</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-expand-lg navbar-light box-shadow mb-3">
            <div class="container">
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="word-break:keep-all">SpookVooper</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="CommunityDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Nerdcraft
                            </a>
                            <div class="dropdown-menu" aria-labelledby="CommunityDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Nerdcraft" asp-action="Index">Home</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nerdcraft" asp-action="RulesGeneral">Rules</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nerdcraft" asp-action="Laws">Laws</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nerdcraft" asp-action="Jobs">Jobs</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nerdcraft" asp-action="Guide">Guide</a>
                            </div>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="News" asp-action="Index">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Exchange" asp-action="Index">Exchange</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="CommunityDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Community
                            </a>
                            <div class="dropdown-menu" aria-labelledby="CommunityDropdown">
                                <a class="dropdown-item" asp-area="" asp-route-id="Root" asp-controller="Forum" asp-action="Index">Forums</a>
                                <a class="dropdown-item" asp-controller="Government" asp-action="Index">Government</a>
                                <a class="dropdown-item" asp-controller="Leaderboard" asp-action="Index">Leaderboard</a>
                                <a class="dropdown-item" asp-controller="Government" asp-action="Map">Districts</a>
                                <a class="dropdown-item" asp-controller="Government" asp-action="Elections">Elections</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="SearchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                People
                            </a>
                            <div class="dropdown-menu" aria-labelledby="SearchDropdown">
                                @{
                                    User user = null;
                                    if (User != null) { user = await userManager.GetUserAsync(User); }

                                    if (user != null)
                                    {
                                        <a class="dropdown-item" asp-controller="Manage" asp-action="Index">My Account</a>
                                        <a class="dropdown-item" asp-controller="User" asp-action="Info" asp-route-svid="@user.Id">My Page</a>
                                    }
                                    else
                                    {
                                        <a class="dropdown-item" asp-controller="Manage" asp-action="Index" disabled>My Account</a>
                                        <a class="dropdown-item" asp-controller="User" asp-action="Info" disabled>My Page</a>
                                    }
                                }

                                <a class="dropdown-item" asp-controller="User" asp-action="Search">Find</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="GroupDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Groups
                            </a>
                            <div class="dropdown-menu" aria-labelledby="GroupDropdown">
                                <a class="dropdown-item" asp-controller="Group" asp-action="Create">Create</a>
                                <a class="dropdown-item" asp-controller="Group" asp-action="MyGroups">My Groups</a>
                                <a class="dropdown-item" asp-controller="Group" asp-action="Search">Find</a>
                            </div>
                        </li>
                    </ul>
                </div>

                <div>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="d-flex justify-content-between">
                <div class="p-1">
                    &copy; 2019-2021 - Vooper Media LLC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
                <div class="p-10" />
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SpookVooper/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = (Model.StartsWith("Error") || Model.Contains("Failed")) ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}