SpookVooper/Controllers/GovernmentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.Models.GovernmentViewModels;
using SpookVooper.Web.Services;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using SpookVooper.Web.Helpers;
using Microsoft.EntityFrameworkCore;
using Discord;
using SpookVooper.Web.Entities;
using SpookVooper.Web.DB;
using SpookVooper.Web.Government;
using SpookVooper.Web.Government.Voting;

namespace SpookVooper.Web.Controllers
{

    [Route("[controller]/[action]")]
    public class GovernmentController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        public GovernmentController(
            VooperContext context,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> Index()
        {
            GovernmentIndexModel model = new GovernmentIndexModel();

            await Task.Run(() =>
            {
                model.president = VoopAI.server.Users.FirstOrDefault(u => u.Roles.Any(r => r.Id == 478312333723041792));
                model.vicePresident = VoopAI.server.Users.FirstOrDefault(u => u.Roles.Any(r => r.Id == 607416531487424513));
                model.justices = VoopAI.server.Users.Where(u => u.Roles.Any(r => r.Id == 695367302564151458));
            });

            model.server = VoopAI.govServer;

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> MoveDistrict(string districtname)
        {
            District district = _context.Districts.FirstOrDefault(d => d.Name.ToLower() == districtname.ToLower());

            if (district == null)
            {
                StatusMessage = $"Error: Could not find {districtname}!";
                return Redirect(Request.Headers["Referer"].ToString());
            }

            User user = await _userManager.GetUserAsync(User);

            if (user.district_move_date != null)
            {
                var daysWaited = Math.Round(DateTime.Now.Subtract(user.district_move_date.Value).TotalDays, 0);

                if (daysWaited < 60)
                {
                    StatusMessage = $"Error: You must wait another {60 - daysWaited} days to move again!";
                    return Redirect(Request.Headers["Referer"].ToString());
                }
            }

            user.district = district.Name;

            if (!string.IsNullOrWhiteSpace(user.district))
            {
                user.district_move_date = DateTime.Now;
            }

            await _userManager.UpdateAsync(user);

            StatusMessage = $"You have moved to {districtname}!";

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public async Task<IActionResult> Map()
        {
            return View();
        }

        public async Task<IActionResult> PolMap()
        {
            return View();
        }

        public async Task<ActionResult> ViewDistrict(string id)
        {
            if (id == null)
            {
                id = "";
            }

            District district = _context.Districts.FirstOrDefault(d => d.Name.ToLower() == id.ToLower());

            return View(district);
        }

        [HttpGet]
        [AuthorizeDiscord("Senator,Emperor")]
        public async Task<IActionResult> EditDistrict(string id)
        {
            if (id == null)
            {
                id = "";
            }

            User user = await _userManager.GetUserAsync(User);

            District district = _context.Districts.AsNoTracking().FirstOrDefault(d => d.Name.ToLower() == id.ToLower());

            if (district == null)
            {
                StatusMessage = $"Could not find the district {id}!";
                return View();
            }

            if (district.Senator != user.Id)
            {
                StatusMessage = $"Could not find the district {id}!";
                return View();
            }

            //if (district == null)
            //{
            //    district = new District();
            //}

            return View(district);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditDistrict(District model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            District old = await _context.Districts.AsNoTracking().AsQueryable().FirstOrDefaultAsync(x => x.Name == model.Name);

            User user = await _userManager.GetUserAsync(User);

            if (user.Id != old.Senator)
            {
                StatusMessage = "Failed: You do not have permission to edit this district!";
                return View();
            }

            if (!(await _context.Districts.AsQueryable().AnyAsync(d => d.Name.ToLower() == model.Name.ToLower())))
            {
                _context.Districts.Add(model);
            }
            else
            {


                // Ensure senator is not changed
                model.Senator = old.Senator;

                _context.Districts.Update(model);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("ViewDistrict", new { id = model.Name });
        }

        [HttpGet]
        [Authorize]
        [AuthorizeDiscord("Senator,Emperor,Prime Minister,Board of MOF")]
        public async Task<IActionResult> Budget()
        {
            return View();
        }

        public async Task<IActionResult> Elections()
        {
            var current = _context.Elections.AsQueryable().Where(x => x.Active);

            return View(current);
        }

        [Authorize]
        [AuthorizeGov("Ministry of Elections")]
        public async Task<IActionResult> ManageElections()
        {
            var current = _context.Elections.AsQueryable().Where(x => x.Active);

            return View(current);
        }

        [HttpGet]
        [Authorize]
        [AuthorizeGov("Ministry of Elections")]
        public async Task<IActionResult> StartElection()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [AuthorizeGov("Ministry of Elections")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StartElection(Election model)
        {
            model.Start_Date = DateTime.UtcNow;
            model.End_Date = DateTime.UtcNow.AddDays(1);
            model.Active = true;

            model.Id = Guid.NewGuid().ToString();

            await _context.Elections.AddAsync(model);
            await _context.SaveChangesAsync();

            StatusMessage = "Successfully started election.";

            EmbedBuilder embed = new EmbedBuilder()
            {
                Color = new Color(0, 100, 255),
                Title = $"**{model.District}** Elections have begun!"
            }
            .WithCurrentTimestamp();

            embed.AddField("News Outlet", "VoopAI Auto News");
            embed.AddField("Author", "VoopAI The Bot");
            embed.AddField("Content", $"Elections have begun in {model.District}! If you are a local, make sure to vote and represent " +
                $"yourself in the district's political system. You can vote on the website under the 'Community->Elections' tab. Please check " +
                $"other news sources for more info!");

            VoopAI.newsChannel.SendMessageAsync(embed: embed.Build());

            return RedirectToAction("Elections");
        }

        [Authorize]
        [AuthorizeGov("Ministry of Elections")]
        public async Task<IActionResult> EndElection(string id)
        {
            Election election = await _context.Elections.FindAsync(id);

            if (election == null)
            {
                StatusMessage = $"Error: Could not find election with Id {id}";
                return RedirectToAction("ManageElections");
            }

            election.End_Date = DateTime.UtcNow;

            _context.Elections.Update(election);
            await _context.SaveChangesAsync();

            EmbedBuilder embed = new EmbedBuilder()
            {
                Color = new Color(0, 100, 255),
                Title = $"**{election.District}** Elections called early!"
            }
            .WithCurrentTimestamp();

            embed.AddField("News Outlet", "VoopAI Auto News");
            embed.AddField("Author", "VoopAI The Bot");
            embed.AddField("Content", $"Elections have been called early in {election.District}! Although I am unable to explain why, " +
                $"this will likely be expanded upon in the other news stations. Stay tuned!");

            VoopAI.newsChannel.SendMessageAsync(embed: embed.Build());

            StatusMessage = $"Successfully set election to end.";
            return RedirectToAction("ManageElections");
        }


        [HttpGet]
        [Authorize]
        [AuthorizeGov("Ministry of Elections")]
        public async Task<IActionResult> IssuePass()
        {

SpookVooper/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpookVooper.Data.Services;
using SpookVooper.VoopAIService;
using SpookVooper.Web.Services;
using System.Linq;
using System.Threading.Tasks;
using Discord.WebSocket;
using SpookVooper.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using SpookVooper.Web.Entities;
using SpookVooper.Web.DB;

namespace SpookVooper.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly VooperContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly IConnectionHandler _connectionHandler;

        public UserController(
            VooperContext context,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            IConnectionHandler connectionHandler)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _connectionHandler = connectionHandler;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string id)
        {
            UserSearchModel model = new UserSearchModel()
            {
                userManager = _userManager,
                search = id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(UserSearchModel model)
        {
            model.userManager = _userManager;

            return RedirectToAction(nameof(Search), routeValues: new { id = model.search });
        }

        [HttpGet]
        public async Task<IActionResult> Info(string svid)
        {
            if (svid == null)
            {
                return View(null);
            }

            User webUser = await _userManager.FindByIdAsync(svid);

            return View(webUser);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> SetInfo()
        {
            User webuser = await _userManager.GetUserAsync(User);

            if (webuser == null)
            {
                return RedirectToAction(nameof(Info));
            }

            SetInfoViewModel model = new SetInfoViewModel()
            {
                Description = webuser.description,
                userManager = _userManager
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetInfo(SetInfoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                model.StatusMessage = "Failed to set: User instance not found!";
                return View(model);
            }

            if (model.Description.Length < 1000)
            {
                user.description = model.Description;
            }
            else
            {
                model.StatusMessage = "Error: The entered description is over 1000 characters!";
                return View(model);
            }

            await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(SetInfo));
        }

        public async Task<IActionResult> GetSVIDFromUsername(string username)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.UserName == username));

            if (user == null) return NotFound($"Could not find user {username}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> GetUsernameFromDiscord(ulong discordid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.discord_id == discordid));

            if (user == null) return NotFound($"Could not find user with discord {discordid}");

            return Ok(user.UserName);
        }

        public async Task<IActionResult> GetSVIDFromDiscord(ulong discordid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.discord_id == discordid));

            if (user == null) return NotFound($"Could not find user with discord {discordid}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> GetUsernameFromMinecraft(string minecraftid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.minecraft_id == minecraftid));

            if (user == null) return NotFound($"Could not find user with minecraft {minecraftid}");

            return Ok(user.UserName);
        }

        public async Task<IActionResult> GetSVIDFromMinecraft(string minecraftid)
        {
            User user = await Task.Run(() => _context.Users.FirstOrDefault(x => x.minecraft_id == minecraftid));

            if (user == null) return NotFound($"Could not find user with minecraft {minecraftid}");

            return Ok(user.Id);
        }

        public async Task<IActionResult> HasDiscordRole(string userid, string role)
        {
            User user = await _userManager.FindByIdAsync(userid);

            if (user == null) return NotFound($"Could not find {userid}");
            else
            {
                SocketGuildUser discordUser = VoopAI.server.Users.FirstOrDefault(u => u.Id == user.discord_id);

                if (discordUser == null) return NotFound($"User has no linked discord account!");

                else return Ok(discordUser.Roles.Any(r => r.Name.ToLower() == role.ToLower()));
            }
        }

        public async Task<IActionResult> GetDiscordRoles(string userid)
        {
            User user = await _userManager.FindByIdAsync(userid);

            if (user == null) return NotFound($"Could not find user {userid}.");

            if (user.discord_id == null) return NotFound($"User does not have a linked discord.");

            var roles = VoopAI.server.GetUser((ulong)user.discord_id).Roles;

            string data = "";

            if (roles.Count > 0)
            {
                foreach (var role in roles)
                {
                    data += role.Name + "|";
                }

                data = data.Substring(0, data.Length - 1);
            }

            return Ok(data);

        }
    }
}

SpookVooper/Views/Government/Elections.cshtml
@model IEnumerable<Election>
@inject VooperContext context

@{
    ViewData["Title"] = "Senate Elections";
}

<head>
    <meta property="og:title" content="Vooperia Senate Elections">
    <meta name="keywords" content="SpookVooper, Economy, News">
    <meta property="og:description" content="The place to vote in and view Senate elections">
    <meta property="og:url" content="https://spookvooper.com/Government/SenateElection">
</head>


<!-- Main row for page -->
<div class="d-flex flex-row align-content-center" style="width:100%">
    <!-- Leftmost column -->
    <div class="p-4 flex-shrink-1 ml-auto"></div>
    <!-- Center column -->
    <div class="p-4" style="width:80em">
        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])
        <h1 class="display-2 text-center">Senate Elections</h1>

        @if (Model == null || Model.Count() == 0)
        {
            <h2 class="text-center">There are no current elections.</h2>
        }
        else
        {
            foreach (Election election in Model)
            {
                <hr class="stock-square-hr" />
                <a asp-controller="Government" asp-action="ViewElection" asp-route-id="@election.Id">
                    <h2>@election.District</h2>
                </a>
                <h2>Ends: @election.End_Date.ToLocalTime().ToShortDateString() @@ @election.End_Date.ToLocalTime().ToShortTimeString()</h2>
                <br />
            }
        }
    </div>
    <!-- Rightmost column -->
    <div class="p-4 flex-shrink-1 mr-auto"></div>
</div>

SpookVooper/Views/Government/ManageElections.cshtml
@model IEnumerable<Election>
@inject VooperContext context

@{
    ViewData["Title"] = "Senate Elections";
}

<head>
    <meta property="og:title" content="Manage Vooperia Senate Elections">
    <meta name="keywords" content="SpookVooper, Economy, News">
    <meta property="og:description" content="The place to modify and plan elections">
    <meta property="og:url" content="https://spookvooper.com/Government/ManageSenateElection">
</head>


<!-- Main row for page -->
<div class="d-flex flex-row align-content-center" style="width:100%">
    <!-- Leftmost column -->
    <div class="p-4 flex-shrink-1 ml-auto"></div>
    <!-- Center column -->
    <div class="p-4" style="width:80em">
        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])
        <h1 class="display-2 text-center">Election Manager Controls</h1>

        @if (Model == null || Model.Count() == 0)
        {
            <h2 class="text-center">There are no current elections.</h2>
        }
        else
        {
            foreach (Election election in Model)
            {
                <hr />
                <h2 class="text-center">@election.District</h2>
                <h2 class="text-center">Ends: @election.End_Date.ToLocalTime().ToShortDateString() @@ @election.End_Date.ToLocalTime().ToShortTimeString()</h2>
                <div class="text-center">
                    <a class="btn btn-outline-warning" asp-action="EndElection" asp-controller="Government" asp-route-id="@election.Id">Call Early</a>
                    <a class="btn btn-outline-warning" asp-action="ViewVotes" asp-controller="Government" asp-route-id="@election.Id">View Votes</a>
                </div>
                <br />
            }
        }

        <br />

        <div class="text-center">
            <a class="btn btn-outline-primary" asp-action="StartElection" asp-controller="Government">Start an Election</a>
        </div>
        <div class="text-center">
            <a class="btn btn-outline-primary" style="margin-top:5px" asp-action="IssuePass" asp-controller="Government">Allow or Block Candidate</a>
        </div>

    </div>
    <!-- Rightmost column -->
    <div class="p-4 flex-shrink-1 mr-auto"></div>
</div>

SpookVooper/Views/Government/ViewDistrict.cshtml
@model District
@inject UserManager<User> userManager
@inject VooperContext context

@{ 
    if (Model != null)
    {
        ViewData["Title"] = Model.Name;
    }
}

<head>
    <meta property="og:title" content="@StringHelper.FormatTitle(Model.Name, 20)">
    <meta name="keywords" content="SpookVooper, Vooperia, Districts, Government">
    <meta property="og:description" content="@StringHelper.FormatTitle(Model.Description, 50)">
    <meta property="og:url" content="https://spookvooper.com/Government/ViewDistrict/@Model.Name">
</head>

<!-- Main row for page -->
<div class="d-flex flex-row align-content-center" style="width:100%">
    <!-- Leftmost column -->
    <div class="p-2 flex-shrink-1 ml-auto"></div>

    <!-- Center column -->
    <div class="p-4" style="width:80em">

        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])

        @{
            if (Model != null)
            {

                var senator = await Model.GetSenator(context);
                var user = await userManager.GetUserAsync(User);

                if (user != null && senator != null && (senator.Id == user.Id || user.UserName == "SpikeViper"))
                {
                    <a asp-route-id="@Model.Name" asp-action="EditDistrict" asp-controller="Government" class="btn btn-primary">Modify</a>
                }

                <div class="d-flex align-content-center align-items-center">

                    <div class="ml-auto" style="display: inline-block; vertical-align:central; height:100%">
                        <img src="@Model.Flag_Url" style="width:5em; vertical-align:middle" />
                    </div>

                    <div style="display:inline-block; margin:2em;">
                        <h2 style="text-align:center" class="display-4">The District of</h2>
                        <h1 style="text-align:center" class="display-3">@Model.Name</h1>
                    </div>

                    <div class="mr-auto" style="display: inline-block; vertical-align:central; height:100%">
                        <img src="@Model.Flag_Url" style="width:5em; vertical-align:middle" />
                    </div>

                </div>

                <br />

                if (senator != null)
                {
                    <div class="p-2 align-self-center" style="text-align:center">

                        @{
                            string senateName = "None.";
                            if (senator != null)
                            {
                                senateName = senator.Name;
                            }
                        }

                        <h2>Elected Senator: @senateName</h2>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4"></div>
                                <div class="col-sm-4 col-sm-offset-4">
                                    <div>
                                        @if (senator != null)
                                        {
                                            var party = senator.GetParty();
                                            var color = new Discord.Color(255, 255, 255);

                                            if (party != null)
                                            {
                                                color = party.Color;
                                            }

                                            <br />
                                            <img class="govpfp" style="box-shadow: 0px 0px 0px 7px rgb(@color.R, @color.G, @color.B);" src="@senator.GetPfpUrl()" />
                                        }
                                    </div>
                                </div>
                                <div class="col-sm-4"></div>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="p-2 align-self-center" style="text-align:center">
                        <h3>Elected Senator: None!</h3>
                    </div>
                }

                int population = userManager.Users.Count(u => !string.IsNullOrWhiteSpace(u.district) && u.district.ToLower() == Model.Name.ToLower());

                <div class="p-2 align-self-center" style="text-align:center">
                    <h3>Population: @population</h3>
                </div>

                if (user != null)
                {
                    if (user.district != null && user.district.ToLower() == Model.Name.ToLower())
                    {
                        <div class="p-2 align-self-center" style="text-align:center">
                            <h3>You live here.</h3>
                        </div>
                    }
                    else
                    {
                        <div class="p-2 align-self-center" style="text-align:center">
                            <a asp-action="MoveDistrict" asp-controller="Government" asp-route-districtname="@Model.Name" class="btn btn-outline-primary">Move Here</a>
                        </div>
                    }
                }
                else
                {
                    <div class="p-2 align-self-center" style="text-align:center">
                        <h3>Log in to move!</h3>
                    </div>
                }

                <br />
                <br />
                <br />
                <br />

                if (Model.Description != null)
                {
                    <h1 style="text-align:left">Description</h1>
                    <p class="p" style="font-size:large">@Html.Raw(@Markdown.Parse(Model.Description, sanitizeHtml: true))</p>
                }

                <br />
                <hr />



                var posts = context.ForumPosts.AsQueryable().Where(c => !c.Removed && c.Category == Model.Name).AsEnumerable().OrderBy(c => DateTime.UtcNow.Subtract(c.TimePosted).TotalSeconds).Take(5).ToList();

                if (posts.Count > 0)
                {
                    <h1>Recent Posts</h1>
                }


                for (int i = 0; i < 5; i++)
                {
                    if (i > posts.Count() - 1)
                    {
                        break;
                    }

                    ForumPost post = posts[i];

                    <div class="d-flex flex-wrap srow">
                        <div class="p-2" style="font-size:larger">
                            💙 @post.GetLikes(context)
                        </div>
                        <div class="p-2" style="width:40%">

                            <a style="font-size:larger" asp-controller="Forum" asp-action="ViewPost" asp-route-id="@post.PostID">
                                @StringHelper.FormatTitle(post.Title, 20)
                            </a>
                        </div>

                        <div class="p-0 flex-grow-1">
                            <div class="d-flex">
                                @{
                                    User authorUser = await userManager.FindByIdAsync(post.Author);
                                    <div class="p-1">
                                        <img class="smallpfp" style="margin-left: 10px; margin-right:10px; float:right" src="@authorUser.GetPfpUrl()" />
                                    </div>
                                    <a asp-controller="User" asp-action="Info" asp-route-id="@authorUser.UserName">
                                        <p class="forumtable-text">@authorUser.UserName</p>
                                    </a>
                                }
                            </div>
                        </div>

                        <div class="p-2" style="min-width:25%">
                            <p style="word-break:break-all">
                                @StringHelper.FormatTitle(post.Content, 30)
                            </p>
                        </div>
                        <!--
                            <div class="col-3">
                                <p style="font-size:smaller">
                                    @post.Tags
                                </p>
                            </div>
                        -->

                    </div>
                }
            }
            else
            {
                <h1 style="text-align:center" class="display-4">District not found!</h1>
            }
        }
    </div>

    <!-- Rightmost column -->
    <div class="p-4 flex-shrink-1 mr-auto"></div>
</div>

SpookVooper/Views/Government/ViewVotes.cshtml
@model Election
@inject UserManager<User> userManager
@inject VooperContext context

@{
    string title = "Could not find district!";

    if (Model != null)
    {
        title = Model.District + " " + Model.Type + " Votes";
        ViewData["Title"] = title;
    }
}

<head>
    <meta property="og:title" content="@title">
    <meta name="keywords" content="SpookVooper, Vooperia, Districts, Government, Elections">
    <meta property="og:description" content="Elections results">
    <meta property="og:url" content="https://spookvooper.com/Government/ViewVotes?id=@Model.Id">
</head>

<!-- Main row for page -->
<div class="d-flex flex-row align-content-center" style="width:100%">
    <!-- Leftmost column -->
    <div class="p-2 flex-shrink-1 ml-auto"></div>

    <!-- Center column -->
    <div class="p-4" style="width:80em">

        @await Html.PartialAsync("_StatusMessage", TempData["StatusMessage"])

        <table class="table">
            <tr>
                <th>Name</th>
                <th>Total XP</th>
                <th>Balance</th>
                <th>District</th>
                <th>Vote Time</th>
                <th>Invalid</th>
                <th>Options</th>
            </tr>
            @foreach (var vote in context.ElectionVotes.AsQueryable().Where(x => x.Election_Id == Model.Id))
            {
                User voter = await context.Users.FindAsync(vote.User_Id);

                if (voter != null)
                {
                    <tr>
                        <td>@voter.UserName</td>
                        <td>@voter.GetTotalXP()</td>
                        <td>@voter.Credits</td>
                        <td>@voter.district</td>
                        <td>@vote.Date.ToLocalTime().ToShortDateString() @@ @vote.Date.ToLocalTime().ToShortTimeString()</td>
                        <td>@vote.Invalid</td>
                        @if (!vote.Invalid)
                        {
                            <td><a class="btn btn-outline-danger" asp-controller="Government" asp-action="InvalidateVote" asp-route-id="@vote.Id">Invalidate</a></td>
                        }
                        else
                        {
                            <td><a class="btn btn-outline-warning" asp-controller="Government" asp-action="InvalidateVote" asp-route-id="@vote.Id">Revalidate</a></td>
                        }
                    </tr>
                }

            }
        </table>




    </div>

    <!-- Rightmost column -->
    <div class="p-4 flex-shrink-1 mr-auto"></div>
</div>